version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bytes
    versions:
    - ">= 0.5.a, < 0.6"
  - dependency-name: bytes
    versions:
    - ">= 0.6.a, < 0.7"
  - dependency-name: bytes
    versions:
    - ">= 1.a, < 2"
  - dependency-name: futures
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: mio
    versions:
    - ">= 0.7.a, < 0.8"
  - dependency-name: tokio
    versions:
    - ">= 0.2.a, < 0.3"
  - dependency-name: tokio
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: tokio
    versions:
    - ">= 1.a, < 2"
  - dependency-name: tokio-signal
    versions:
    - "< 0.3, >= 0.2.a"
  - dependency-name: tokio-uds
    versions:
    - "< 0.3, >= 0.2.a"
  - dependency-name: libc
    versions:
    - 0.2.91
